<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BlueNode-Setup</AssemblyName>
    <Version>0.1.5</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <EmbeddedResource Include="payload.zip" LogicalName="BlueNode.Payload" />
    <EmbeddedResource Include="licenses/*.txt" />
  </ItemGroup>
</Project>
