using System.IO.Compression;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using Renci.SshNet;

namespace BlueNode.Setup;

internal sealed class NodeSession : IDisposable
{
    private readonly SshClient ssh;
    private readonly SftpClient sftp;
    private readonly string sudoSecret;
    private readonly string remote = "/tmp/bluenode-desktop-" + Guid.NewGuid().ToString("N");
    private ForwardedPortLocal? tunnel;
    private bool uploaded;

    public NodeSession(string host, int port, string user, string secret, string key,
                       string sudoPassword, Func<string, string, bool> trust)
    {
        host = host.Trim(); user = user.Trim();
        if (host.Length > 253 || !Regex.IsMatch(host, @"\A[a-zA-Z0-9][a-zA-Z0-9.:-]*\z") ||
            port < 1 || port > 65535 || !Regex.IsMatch(user, @"\A[a-zA-Z_][a-zA-Z0-9_.-]*\z"))
            throw new ArgumentException("Enter your node's IP address or hostname and Linux username.");
        sudoSecret = sudoPassword.Length > 0 ? sudoPassword : (key.Length == 0 ? secret : "");
        AuthenticationMethod Auth() => key.Length == 0
            ? new PasswordAuthenticationMethod(user, secret)
            : new PrivateKeyAuthenticationMethod(user, new PrivateKeyFile(key, secret));
        ConnectionInfo Info() => new(host, port, user, Auth()) { Timeout = TimeSpan.FromSeconds(15) };
        ssh = new SshClient(Info()); sftp = new SftpClient(Info());
        string? accepted = null;
        void Verify(object? sender, Renci.SshNet.Common.HostKeyEventArgs args)
        {
            var fingerprint = "SHA256:" + Convert.ToBase64String(SHA256.HashData(args.HostKey)).TrimEnd('=');
            if (accepted == null && trust(host + ":" + port, fingerprint)) accepted = fingerprint;
            args.CanTrust = accepted == fingerprint;
        }
        ssh.HostKeyReceived += Verify; sftp.HostKeyReceived += Verify;
    }

    public void Connect()
    {
        ssh.Connect(); sftp.Connect();
        sftp.CreateDirectory(remote); uploaded = true;
        sftp.ChangePermissions(remote, 700); // SSH.NET takes the decimal digits of the octal mode.
        using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("BlueNode.Payload")!;
        using var archive = new ZipArchive(stream);
        var directories = new HashSet<string> { remote };
        foreach (var entry in archive.Entries)
        {
            if (entry.FullName.Split('/').Any(x => x is ".." or "." or "") || entry.FullName.Contains('\\'))
                throw new InvalidDataException("Invalid release payload path.");
            var parts = entry.FullName.Split('/');
            var parent = remote;
            foreach (var part in parts[..^1])
            {
                parent += "/" + part;
                if (directories.Add(parent)) sftp.CreateDirectory(parent);
            }
            using var content = entry.Open();
            sftp.UploadFile(content, remote + "/" + entry.FullName);
        }
        uploaded = true;
    }

    public async Task<JsonObject> Request(object request)
    {
        var encoded = Convert.ToBase64String(System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(request));
        // Both command arguments are generated by us; never interpolate user input.
        using var command = ssh.CreateCommand("sudo -S -p '' /usr/bin/python3 -u " + remote +
                                              "/install/desktop_bridge.py '" + encoded + "'");
        command.CommandTimeout = TimeSpan.FromSeconds(120);
        var execute = command.ExecuteAsync();
        using (var input = command.CreateInputStream())
        {
            var bytes = Encoding.UTF8.GetBytes(sudoSecret + "\n");
            try { await input.WriteAsync(bytes); }
            finally { CryptographicOperations.ZeroMemory(bytes); }
        }
        await execute;
        // Raw SSH/sudo output is deliberately not displayed or saved.
        JsonObject? result = null;
        try { result = JsonNode.Parse(command.Result.Trim()) as JsonObject; } catch (System.Text.Json.JsonException) { }
        if (result == null)
            throw new InvalidOperationException("The node could not run setup. Check that Python 3 is installed and this Linux login has sudo access. If needed, enter its sudo password under Advanced.");
        if (result["ok"]?.GetValue<bool>() != true)
            throw new InvalidOperationException(result["message"]?.GetValue<string>() ?? "The node could not complete this check.");
        return result;
    }

    public string OpenTunnel(JsonObject station)
    {
        var host = station["host"]!.GetValue<string>();
        var port = station["port"]!.GetValue<uint>();
        if (!System.Net.IPAddress.TryParse(host, out var address) ||
            address.AddressFamily != System.Net.Sockets.AddressFamily.InterNetwork || port < 1024 || port > 65535)
            throw new InvalidDataException("Unsupported dashboard address.");
        tunnel?.Stop(); tunnel?.Dispose();
        tunnel = new ForwardedPortLocal("127.0.0.1", 0, host, port);
        ssh.AddForwardedPort(tunnel); tunnel.Start();
        var page = station["welcome"]?.GetValue<bool>() == true ? "welcome.html" : "";
        return $"http://127.0.0.1:{tunnel.BoundPort}/web/{page}";
    }

    public void Dispose()
    {
        tunnel?.Dispose();
        try
        {
            // Generated directory only. Do not traverse symlinks on the node.
            if (sftp.IsConnected && uploaded) DeleteDirectory(remote);
        }
        catch { /* Connection loss must not prevent closing the app. */ }
        sftp.Dispose(); ssh.Dispose();
    }

    private void DeleteDirectory(string path)
    {
        foreach (var entry in sftp.ListDirectory(path))
        {
            if (entry.Name is "." or "..") continue;
            if (entry.IsDirectory && !entry.IsSymbolicLink) DeleteDirectory(entry.FullName);
            else sftp.DeleteFile(entry.FullName);
        }
        sftp.DeleteDirectory(path);
    }
}
